---
title: "EMD & FFT"
author: "Robert"
date: "2/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Simulate 3 signals, two similar and one different,
perform EMD, extract main FFT coeficients from IMF's and compare FFT coeficients


```{r include=FALSE}
main_coef = function(x, n) {
  order(x, decreasing = T)[1:n]
}

```



Simulate signals

```{r}

xs <- seq(-2*pi, 2*pi, length = 150)
noise <- rnorm(150, 2, 9)

wave_1 <- 5*sin(30*xs) + cos(5*xs) + noise
wave_2 <- 5*sin(30*xs) + cos(10*xs) + noise
wave_3 <- 8*sin(40*xs) + 0.4*cos(26*xs) + sin(14*xs) + noise
```



Periodograms

```{r echo=FALSE}
par(mfrow=c(2,2))
TSA::periodogram(wave_1, ylab = "wave 1")
TSA::periodogram(wave_2, ylab = "wave 2")
TSA::periodogram(wave_3, ylab = "wave 3")
TSA::periodogram(noise, ylab = "noise")

```


Plot signals

```{r echo=FALSE}
par(mfrow=c(2,2))
plot(wave_1, type = 'l')
plot(wave_2, type = 'l')
plot(wave_3, type = 'l')
plot(noise, type = 'l')

```



Perform EMD

```{r echo=FALSE}
emd_wave <- EMD::emd(wave_1)
emd_wave_2 <- EMD::emd(wave_2)
emd_wave_3 <- EMD::emd(wave_3)

cat(' wave_1 imf\'s number:', emd_wave$nimf, '\n',
    'wave_2 imf\'s number:', emd_wave_2$nimf, '\n',
    'wave_3 imf\'s number:', emd_wave_3$nimf, '\n')


```


IMF's and euclidean distance and main FFT coef's

```{r echo=FALSE}
# extract 1st imf's
imf_1_1 <- emd_wave$imf[,1]
imf_1_2 <- emd_wave_2$imf[,1]
imf_1_3 <- emd_wave_3$imf[,1]

par(mfrow=c(3,1))
# 1st imf's plot
plot(imf_1_1, type = 'l')
plot(imf_1_2, type = 'l')
plot(imf_1_3, type = 'l')
 
# 1st imf's main fft coeficients
fft_1_1 <- stats::fft(imf_1_1)
coef_1_1 <- main_coef(fft_1_1, 10)  
fft_1_2 <- stats::fft(imf_1_2)
coef_1_2 <- main_coef(fft_1_2, 10)  
fft_1_3 <- stats::fft(imf_1_3)
coef_1_3 <- main_coef(fft_1_3, 10)  
# coeficients table
tbl_1 <- data.frame(Mod(fft_1_1[coef_1_1]), Mod(fft_1_2[coef_1_2]), Mod(fft_1_3[coef_1_3]))
print(tbl_1)

# calculate distance between 1st imf's
dist(rbind(
  imf_1_1, imf_1_2, imf_1_3
))

#2nd imf's
imf_2_1 <- emd_wave$imf[,2]
imf_2_2 <- emd_wave_2$imf[,2]
imf_2_3 <- emd_wave_3$imf[,2]

# 2nd imf's plot
plot(imf_2_1, type = 'l')
plot(imf_2_2, type = 'l')
plot(imf_2_3, type = 'l')

# calculate distance between 2st imf's
dist(rbind(
  imf_2_1, imf_2_2, imf_2_3
))
# 2nd imf's main fft coeficients
fft_2_1 <- stats::fft(imf_2_1)
coef_2_1 <- main_coef(fft_2_1, 10)  
fft_2_2 <- stats::fft(imf_2_2)
coef_2_2 <- main_coef(fft_2_2, 10)  
fft_2_3 <- stats::fft(imf_2_3)
coef_2_3 <- main_coef(fft_2_3, 10)  
# coeficients table
tbl_2 <- data.frame(coef_2_1, coef_2_2, coef_2_3)
print(tbl_2)


# extract 3rd imf's
imf_3_1 <- emd_wave$imf[,3]
imf_3_2 <- emd_wave_2$imf[,3]
imf_3_3 <- emd_wave_3$imf[,3]

# 3rd imf's plot
plot(imf_3_1, type = 'l')
plot(imf_3_2, type = 'l')
plot(imf_3_3, type = 'l')

# calculate distance between 3rs imf's
dist(rbind( ## we can see obvious different between waves
  imf_3_1, imf_3_2, imf_3_3 ## and distance shows same result
))   
# 3rd imf's main fft coeficients
fft_3_1 <- stats::fft(imf_3_1)
coef_3_1 <- main_coef(fft_3_1, 10)  
fft_3_2 <- stats::fft(imf_3_2)
coef_3_2 <- main_coef(fft_3_2, 10)  
fft_3_3 <- stats::fft(imf_3_3)
coef_3_3 <- main_coef(fft_3_3, 10)  
# coeficients table
tbl_3 <- data.frame(coef_3_1, coef_3_2, coef_3_3)
print(tbl_3)

# extract 4th imf's
imf_4_1 <- emd_wave$imf[,4]
imf_4_2 <- emd_wave_2$imf[,4]
imf_4_3 <- emd_wave_3$imf[,4]

# 4th imf's plot
plot(imf_4_1, type = 'l')
plot(imf_4_2, type = 'l')
plot(imf_4_3, type = 'l')

# calculate distance between 4th imf's
dist(rbind(
  imf_4_1, imf_4_2, imf_4_3
))
# 4th imf's main fft coeficients
fft_4_1 <- stats::fft(imf_4_1)
coef_4_1 <- main_coef(fft_4_1, 10)  
fft_4_2 <- stats::fft(imf_4_2)
coef_4_2 <- main_coef(fft_4_2, 10)  
fft_4_3 <- stats::fft(imf_4_3)
coef_4_3 <- main_coef(fft_4_3, 10)  
# coeficients table
tbl_4 <- data.frame(coef_4_1, coef_4_2, coef_4_3)
print(tbl_4)

```


# Conclusion:
compared imf's fft coeficients, we can detect even slightly changed signal (wave_1 and wave_2)


